name: 🐞 Bug
description: File a bug/issue
labels: [bug]
body:
- type: textarea
  attributes:
    label: Describe the issue
    description: Briefly explain what you're trying to build and a clear concise description of what you're experiencing.
    placeholder: Ex. I'm building a C# backend for a web app and...
  validations:
    required: false
- type: textarea
  attributes:
    label: Collect logs
    description: |
      Please run the ".NET: Collect C# Dev Kit Logs" command in VS Code and attach the resulting zip file to this issue.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment information
    description: Information about your environment
    placeholder: |
      - OS: [e.g. Windows, macOS, Linux]
      - VS Code Version [e.g. 1.25.1]
      - Extension Version (found in the settings of the extension) [e.g. 1.0.0] 
  validations:
    required: false
