name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [bug]
body:
- type: textarea
  attributes:
    label: Describe the Issue
    description: A clear concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment Information
    description: Information about your environment
    placeholder: |
      - OS: [e.g. Windows, macOS, Linux]
      - VS Code Version [e.g. 1.25.1]
      - Extension Version (found in the settings of the extension) [e.g. 1.0.0] 
  validations:
    required: false
